version: '3'

services:
  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: readwatch-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - readwatch-network

  # Backend API
  backend:
    build:
      context: ./backend
    container_name: readwatch-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/readwatch
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
    depends_on:
      - mongodb
    networks:
      - readwatch-network

  # Frontend
  frontend:
    build:
      context: ./frontend
    container_name: readwatch-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - readwatch-network

networks:
  readwatch-network:
    driver: bridge

volumes:
  mongodb_data: